# tommyq.cz/sport/ - Token-based access control
$HTTP["host"] == "tommyq.cz" {
    $HTTP["url"] =~ "^/sport" {
        $HTTP["querystring"] !~ "token=vYOFavsNQi9MW4V3LbmuLQ" {
            url.redirect = ( "" => "https://tommyq.cz/" )
        }
    }
    $HTTP["url"] =~ "^/sport/cgi/" {
        cgi.assign = ( ".cgi" => "" )
    }
}
