-- Limit cache to 50 MB
cache.size = 50 * MB

-- Načíst modul policy
modules.load('policy')

-- 1. Přepsání *.tommyq.cz i tommyq.cz na 192.168.2.1
policy.add(policy.suffix(
    policy.ANSWER({
        [kres.type.A] = { rdata = kres.str2ip('192.168.2.1'), ttl = 300 }
    }),
    { todname('tommyq.cz') }
))

-- 2. Statické stroje natvrdo v Kresdu (neovlivní je DHCP ani Turris skripty)
policy.add(policy.suffix(
    policy.ANSWER({ [kres.type.A] = { rdata = kres.str2ip('192.168.2.2'), ttl = 300 } }),
    { todname('tiger'), todname('tiger.lan') }
))

policy.add(policy.suffix(
    policy.ANSWER({ [kres.type.A] = { rdata = kres.str2ip('192.168.2.3'), ttl = 300 } }),
    { todname('tiger-win'), todname('tiger-win.lan') }
))

policy.add(policy.suffix(
    policy.ANSWER({ [kres.type.A] = { rdata = kres.str2ip('192.168.2.4'), ttl = 300 } }),
    { todname('leo'), todname('leo.lan') }
))

policy.add(policy.suffix(
    policy.ANSWER({ [kres.type.A] = { rdata = kres.str2ip('10.111.111.2'), ttl = 300 } }),
    { todname('panther'), todname('panther.lan') }
))